[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_defs = True
ignore_missing_imports = False

[mypy-tests.*]
disable_error_code = var-annotated

[mypy-script.*]
ignore_errors = True

[mypy-ejemplos.*]
ignore_errors = True
