name: CI

on:
  push:
  pull_request:

jobs:
  lint-test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (black)
        run: black . --exclude '/(ejemplos|scripts|\.github/scripts)/'
      - name: Format check (black)
        run: black --check . --exclude '/(ejemplos|scripts|\.github/scripts)/'
      - name: PEP8 (flake8)
        run: flake8 --exclude scripts,ejemplos --max-line-length 120 --extend-ignore E203,E501
      - name: Docstrings (pydocstyle)
        run: pydocstyle src --ignore D102,D107,D203
      - name: Types (mypy)
        run: mypy src
      - name: Types (pyright)
        run: pyright
      - name: Security (bandit)
        run: bandit -r src
      - name: Tests
        env:
          MPLBACKEND: Agg
        run: pytest
      - name: Build docs (pdoc)
        run: pdoc -o site src/txori
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
