name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install -e .
      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check .
      - name: Flake8 (PEP8)
        run: flake8 src tests
      - name: Pydocstyle (PEP257)
        run: pydocstyle src
      - name: MyPy
        run: mypy src
      - name: Pyright
        run: pyright
      - name: Pytest
        run: pytest
      - name: Bandit
        run: bandit -r src
      - name: Trufflehog
        run: trufflehog filesystem --fail .
      - name: Build docs (pdoc)
        run: pdoc -o docs src/txori
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

  bump-build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Bump build
        run: python .github/scripts/bump_build.py
      - name: Commit build bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump build [skip ci]"
          file_pattern: |
            src/txori/__init__.py
            README.md
            CHANGELOG.md
